-- 0001_init.up.sql — initial schema for the Remote Support MVP.
-- Tables per docs/ARCHITECTURE.md §4. All ids are UUIDs generated by the app.

CREATE TABLE IF NOT EXISTS technicians (
    id            UUID PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name  TEXT NOT NULL DEFAULT '',
    role          TEXT NOT NULL DEFAULT 'technician',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
    id                 UUID PRIMARY KEY,
    name               TEXT NOT NULL DEFAULT '',
    hostname           TEXT NOT NULL DEFAULT '',
    os                 TEXT NOT NULL DEFAULT '',
    device_secret_hash TEXT NOT NULL,
    mode               TEXT NOT NULL DEFAULT 'unattended', -- unattended | attended
    app_version        TEXT NOT NULL DEFAULT '',
    last_seen_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    id             UUID PRIMARY KEY,
    -- NULL until an attended session's ephemeral device is bound at join time.
    device_id      UUID REFERENCES devices(id),
    technician_id  UUID REFERENCES technicians(id),
    type           TEXT NOT NULL,                 -- unattended | attended
    status         TEXT NOT NULL DEFAULT 'pending', -- pending | active | ended
    banner_visible BOOLEAN NOT NULL DEFAULT false,
    started_at     TIMESTAMPTZ,
    ended_at       TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON sessions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_device_id ON sessions (device_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions (status);

-- Append-only audit log. The application never issues UPDATE/DELETE here.
CREATE TABLE IF NOT EXISTS audit_events (
    id            UUID PRIMARY KEY,
    event_type    TEXT NOT NULL,
    session_id    UUID REFERENCES sessions(id),
    technician_id UUID REFERENCES technicians(id),
    device_id     UUID REFERENCES devices(id),
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_events (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_session_id ON audit_events (session_id);
CREATE INDEX IF NOT EXISTS idx_audit_device_id ON audit_events (device_id);
CREATE INDEX IF NOT EXISTS idx_audit_technician_id ON audit_events (technician_id);
CREATE INDEX IF NOT EXISTS idx_audit_event_type ON audit_events (event_type);
